DROP TABLE IF EXISTS Auth;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Auth (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    auth_token TEXT NOT NULL,
    instance_url  TEXT NOT NULL
);

CREATE TABLE Customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    email  TEXT NOT NULL
);